--
-- Здесь нужно регистрировать функции для запуска их кроном
--

-- -------------------------------------------------------------------------------
-- CREATE OR REPLACE VIEW pgcron.jobs AS
--   SELECT schema_name, func_name, run_interval::interval
--     FROM (
--       VALUES
--         ('sys', 'server_cron', '1 min'),
--         ('sys', 'repwork_cron', '1 min'),
--         ('media', 'file_cron', '1 min'),
--         ('media', 'aux_cron', '1 min'),
--         ('media', 'imfgenjob_cron', '1 min'),
--         ('log', 'apirequests_cron', '1 min'),
--         ('media', 'searchable_update', '2 min')
--     ) foo (schema_name, func_name, run_interval);
-- --
-- GRANT SELECT ON TABLE pgcron.jobs TO schema;
-- -------------------------------------------------------------------------------
