---
- name: (re)start pgcron container
  docker_container:
    name: "{{ pgcron_docker_name }}"
    image: "{{ pgcron_docker_image }}"
    network_mode: host
    env:
      PGHOST: "{{ pgcron_host }}"
      PGDATABASE: "{{ pgcron_db }}"
      PGUSER: "{{ pgcron_user }}"
      PGPASSWORD: "{{ pgcron_password }}"
      LOGLEVEL: "{{ pgcron_loglevel }}"
    restart_policy: always
    restart: "{{ __pgcron_restart | default(false) }}"
    pull: true
    state: "started"
